### ISSUE TITLE
publish use cases and scope doc to wiki

### ISSUE THREAD

**Issue by dchud** [gwu-libraries/sfm#15]
Wiki home:

https://github.com/gwu-libraries/sfm/wiki

**Comment by dchud** [comment]
Scope doc: https://github.com/gwu-libraries/sfm/wiki/Project-scope:-Social-Feed-Manager

**Comment by dchud** [comment]
User stories:

https://github.com/gwu-libraries/sfm/wiki/User-story:-Basic-researcher
https://github.com/gwu-libraries/sfm/wiki/User-story:-Event-capture
https://github.com/gwu-libraries/sfm/wiki/User-story:-Archivist
https://github.com/gwu-libraries/sfm/wiki/User-story:-Future-researchers
https://github.com/gwu-libraries/sfm/wiki/User-story:-Collection-review

Wiki home:

https://github.com/gwu-libraries/sfm/wiki

**Comment by lwrubel** [comment]
Minor thing: sfm vs. SFM in the Home page and Project Scope. 

I imagine there will be questions around:
* our timeline
* migration path, whether that is supported
* how we plan to communicate with sfm users / interested parties (beyond posting new info on the wiki)
* related, is the sfm-dev google group for the new repo as well? I'm assuming it is, might be nice to confirm that and put a link/info, possibly in the developers section

The stories look fine to me, acknowledging we have various placeholders and they're subject to change, as you point out.

**Comment by dchud** [comment]
Thanks @lwrubel. Switched to "sfm" in the scope doc, although... maybe it just doesn't matter?  Guess we should decide whether we need a decision on that. :)

Also added link to sfm-dev group under For Developers on wiki home page.

**Comment by kerchner** [comment]
:+1:
